version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      NODE_ENV: development
    restart: always
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge
